image: quay.io/openshift/origin-hello-openshift:4.14
replicaCount: 1
service:
  name: http
  port: 8080
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 300m, memory: 256Mi }
route:
  host: hello-odm-tdv1.apps-crc.testing
