apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: hello
  port:
    targetPort: {{ .Values.service.name }}

